### ISSUE TITLE
Curious

### ISSUE THREAD

**Issue by EysseW** [uku3lig/fractionalgui#1]
What is the point of this mod? Don't get me wrong, I am very excited to see it, but I don't get how it works. I have installed it, but just messes with my GUI scale. Usually way to low, but when I fuck with the settings a bit, it's normal again. How exactly is it supposed to work? Is the menu gui supposed to be different from your in-game HUD?

**Comment by uku3lig** [comment]
no, it just add intermediary steps between vanilla gui scales by doing some wonky mixins, that's why i consider it beta software.

as of how it works, the mod has a config option: the scale. it's the divisor for the gui scale; let's say you have a scale of 5, and your options.txt has guiScale=8, the mod will make it so that minecraft shows things at a gui scale of 8/5=1.6

it is certainly a weird way of making it work but the easiest on the coding side, replacing the integer-based gui scale option with a float one would be way harder, if even possible
